REPOS = """
https://github.com/ffersants/web3-2tud1es
https://github.com/chmerev/candy-machine-v2-mint-solana-ui
https://github.com/augustine76/solana-escrow
https://github.com/nevmyatovmakar/tradebots
https://github.com/nevmyatovmakar/northman
https://github.com/PurpleSquirrelMedia/musical-sniffle
https://github.com/MCuenca11/Web3AuthPOC
https://github.com/DescartesNetwork/interdao.so
https://github.com/TheMartianArmy/Spaceship-V1
https://github.com/Boson-so/quarry
https://github.com/Tincon1/SOLNFTBOT
https://github.com/alvaropaco/nft-sales-bot
https://github.com/spacemandev-git/wormhole-solana-sdk
https://github.com/DappStarter/excited-drokklerbed-jNcr
https://github.com/DappStarter/melodic-buberuet-K8c8
https://github.com/DappStarter/supreme-loorurtur-m7HK
https://github.com/remixie/copycats_game
https://github.com/DappStarter/diligent-rushdrooled-7kW7
https://github.com/jstarry/solana-feed-rs
https://github.com/VictorCodeGeekKwasara/crowdfundjs
https://github.com/Bisonai/orca-api
https://github.com/springrainroni/anchor_transfer
https://github.com/energeticlee/counter_app
https://github.com/mateolafalce/blockssage
https://github.com/0xdeepmehta/lil-introvert
https://github.com/MarEeee/solana_send_lamports
https://github.com/IshaMandaviya/Solana_Escrow
https://github.com/nevmyatovmakar/great-goats
https://github.com/nevmyatovmakar/jikan
https://github.com/nevmyatovmakar/dead-pirates
https://github.com/nevmyatovmakar/pitsoffpercs
https://github.com/coral-xyz/apr-ui
https://github.com/0xsol1id/fudility
https://github.com/Chimp-Bastards/ChimpMarket
https://github.com/shi-ivam/gif-nft-generator
https://github.com/Chimp-Bastards/chimpbastards-webpage
https://github.com/Nikimaru89/Submarine
https://github.com/cyphersnake/solana-events-parser
https://github.com/machacekch/solana-cpp-sdk
https://github.com/donkeizluv/sol-nice-wallet
https://github.com/obsidiansystems/solana-bridges
https://github.com/josentaina/juan
https://github.com/eludius18/Solana-Airdrop
https://github.com/minne-ape-olis/dao-mint-dashboard
https://github.com/phuoctung28/dapp_practice
https://github.com/qasimInvoZone/anchor_rust_calculator
https://github.com/Umairhassan5/calculatordapp
https://github.com/d3fkon/sol-escrow
https://github.com/lucianoacsilva/solana-calculator
https://github.com/nicolaskiprop/blog
https://github.com/kronus-protocol/tictactoe-web
https://github.com/reecen96/Riff-Raffle-Solana-NFT
https://github.com/issalcedo/solona-bpf-program
https://github.com/akshay5995/congenial-palm-tree
https://github.com/maven-live/maven-frontend
https://github.com/nevmyatovmakar/mcsol
https://github.com/cierra2016/Solana-nft-rarity
https://github.com/arthurchen330/Kanon
https://github.com/black-wyvern-dev/MDS-metaplex-mint-mvp
https://github.com/VegetarianOrc/shadow-drive-rust
https://github.com/Parth59/SolanaHackathonSubmit
https://github.com/cryptoxpotato/solana-program-demo
https://github.com/turnyay/solana-seed-to-file
https://github.com/vkomenda/auction
https://github.com/saber-hq/saber-common
https://github.com/vicyyn/sollectify
https://github.com/maaz28/nft-metadata-solana
https://github.com/abnegate/pribs
https://github.com/empire-uts/solana-explorer-fork
https://github.com/JoeHowarth/cpi-example
https://github.com/a-tsibin/donate-solana
https://github.com/Sure-Protocol/sure-v1
https://github.com/CryptoMaxPlanck/investmentdao
https://github.com/openchaindev/chapter-x-p2p-swap
https://github.com/SuperCipher/pubsub-smartcontract
https://github.com/Damin3927/tic-tac-toe
https://github.com/jesusyanez/mint-solana-nft
https://github.com/rahul0tripathi/sol_rent_demo
https://github.com/ZengGang315/solana-dex
https://github.com/ricardocr987/ricardocr987
https://github.com/Dikower/candy-machine
https://github.com/nevmyatovmakar/susanoo
https://github.com/nevmyatovmakar/trippinape
https://github.com/apollo0102/NFT_SOL_CAA
https://github.com/wemersonqueiroz/excaltailwind
https://github.com/NeverLucky711/solendprotocol-liquidator
https://github.com/mtariverx/GigaDAO-v2
https://github.com/cuongnguyenngoc/send-token-with-phantom
https://github.com/wizzeh/governance-rewards-crank
https://github.com/DappStarter/kind-rushdrooled-JWPw
https://github.com/paul-schaaf/solsaver
https://github.com/gching/metaplex-js
https://github.com/super1114/Anchor-AMM
https://github.com/ExtropyIO/solana-course
https://github.com/0xdeepmehta/auto-derive-pda
https://github.com/banke-a/solana-twitter
https://github.com/ZeroQ4/One
https://github.com/itsjenm/solana-escrow-program
https://github.com/DappStarter/precious-gomaku-7wjh
https://github.com/legome0937/CyberApeAge
https://github.com/tinwritescode/react-plats-solana
https://github.com/SoftwareArchitect9817/solana-web3
https://github.com/ZclubWeb3/zclub-solana
https://github.com/ireneio/empty-next
https://github.com/thefracture/fractures-raffles-main
https://github.com/thefracture/fractures-omnium-swap-main
https://github.com/nguyenminhthong2020/solana-dapp
https://github.com/zemse/solana-rust-contract
https://github.com/NorbertBodziony/targeted-airdrop
https://github.com/serpentacademy/Solana-Smart-Contract-u32-serialize-deserialize-
https://github.com/ahlinc/ledger-checks
https://github.com/owentr1369/software_engineer_internship_be
https://github.com/danmt/drill-program-poc
https://github.com/jia1076999758/solana-email
https://github.com/DappStarter/cute-buberuet-H9mW
https://github.com/DappStarter/better-kielele-BzMP
https://github.com/DappStarter/tidy-quewoque-CBDg
https://github.com/DappStarter/zonked-hofobost-WGNR
https://github.com/ProjectLarix/larix-sdk
https://github.com/yongDataScince/site
https://github.com/Vortex-Browser-Software/Vortex-Core
https://github.com/stream-protocol/checkout-donation-platform
https://github.com/DragonProtocol/synft-app
https://github.com/serpentacademy/Validate-Solana-NFT-Holders
https://github.com/XFrogs/project-centuri-frontend
https://github.com/mercurial-finance/stable-swap-n-pool-js
https://github.com/yujuiting/bubble-tea
https://github.com/paul-schaaf/diy_etf_frontend
https://github.com/TeamRaccoons/program-sniffer
https://github.com/wzrdk3lly/solanactf
https://github.com/TheCre8tor/arguments_and_accounts
https://github.com/tauseefk/tofuuu-tokenizer
https://github.com/qasimInvoZone/airdrop
https://github.com/EpicsDAO/dapp-boilerplate
https://github.com/HELIOS-Creators-Inc/helios-blockchain-master
https://github.com/sourabh-garg/escrow-program
https://github.com/osmanbowser/refactored-octo-chainsaw
https://github.com/DappStarter/likable-streetemi-qDbB
https://github.com/DappStarter/elated-taquecit-mJrT
https://github.com/DappStarter/festive-bucehee-qMNL
https://github.com/DappStarter/humorous-gimine-GQMB
https://github.com/mhkmcp/react-anchor
https://github.com/Jonas002/sveltekit-solana
https://github.com/CoachChuckFF/Solana_Treasure_Hunt
https://github.com/deltafi-trade/deltafi-app-v2
https://github.com/Chimp-Bastards/chimp-staking
https://github.com/lucianoacsilva/solana-learning
https://github.com/vietsaclo/Rust.Solana.Tutorial
https://github.com/daeshawnballard/chainlink_solana_dapp
https://github.com/TheCre8tor/epic_project
https://github.com/beekay2706/calculator_Dapp
https://github.com/DevonMartens/Solana-Contracts-dApps
https://github.com/hoang0508/NextJs-Project
https://github.com/muccurly/third_person
https://github.com/babilu-online/blok-host-web
https://github.com/IAmadix/Tr
https://github.com/itswilliam7/react-wallet-adapter-solana
https://github.com/YutaFujii0/small-code
https://github.com/itsfarseen/francium-repro
https://github.com/mrgnlabs/funding-rate-arb
https://github.com/Stepanishin/IKnow-project
https://github.com/DappStarter/coherent-roquonley-LzLk
https://github.com/DappStarter/friendly-hopogirn-tKRN
https://github.com/DappStarter/relieved-strithusrue-MgMK
https://github.com/DappStarter/exotic-aludup-kQWr
https://github.com/DappStarter/calm-akhirney-qkFH
https://github.com/DappStarter/silly-peluque-tBDt
https://github.com/DappStarter/bizarre-cejogib-RJdL
https://github.com/anoushk1234/gift-on-solana
https://github.com/0xdeepmehta/serialize-txs-anchor
https://github.com/d3fkon/sol-spl-escrow
https://github.com/SuperGandhi/Facebook-solana
https://github.com/infomalhaut/SolanaDevCounter
https://github.com/koustubhcodes/soltwt
https://github.com/jaimecobo/fb-solana
https://github.com/Muffintechxyz/brightswap
https://github.com/kajirikajiri/solana
https://github.com/yun-sangho/solana-escrow-demo
https://github.com/trancongduynguyen1997/solana-simple-escrow
https://github.com/okayowlsx/owlsx
https://github.com/timov/candy-achine-ui-1
https://github.com/GriffinMcLennan/Token-Mint
https://github.com/DappStarter/heavenly-boosubi
https://github.com/andrewya856/anchor-hw
https://github.com/nhtera/solana-learning
https://github.com/kevinjanada/arise-solana-program
https://github.com/devatsrs/solana-airdropping
https://github.com/crypt0miester/cm-ui-with-signer
https://github.com/mansijoshi17/Solana-Pay
https://github.com/godmodegalactus/solana_writer
https://github.com/lawmeskiviahs/metaplex_program_library
https://github.com/CoachChuckFF/Coach-Drive
https://github.com/Thabii-manii/tiktok-solana
https://github.com/Azaz234/5
https://github.com/cryptoguru1012/neonomad-staking
https://github.com/Unboxed-Software/solana-intro-frontend
https://github.com/rnike/useless-switch
https://github.com/marinade-finance/marinade-sdk
https://github.com/openchaindev/chapter-x-auction
https://github.com/sadathiq/brightswapcollections
https://github.com/radumarica/booking
https://github.com/Hoon-Dev/Solana-hello-world
https://github.com/rowlanja/Solana-NFT-Marketplace
https://github.com/sori18/style_dog_ui
https://github.com/Tincon1/GOB
https://github.com/abdullahshahid137/solana-spl-token-in-rust
https://github.com/rh0108/rh0108
https://github.com/send4fren/send4fren-ui
https://github.com/DappStarter/witty-ibmemut-FbLb
https://github.com/brendan-mccaffrey/hello-solana
https://github.com/topsmart20/solmonkey_Solana_marketplace
https://github.com/nateshirley/swap-structure
https://github.com/openhaus-dao/tradehaus-program
https://github.com/Moveworld-so/move-nfts
https://github.com/lixiaodog/myfirstApp
https://github.com/Markuwa/testingmintagain
https://github.com/web3dev26/web3toksol2
https://github.com/Tincon1/Goblinz
https://github.com/gsandoval22/SOLegionprueba
https://github.com/youngtrappa/crclub
https://github.com/pengsol/Epic-master
https://github.com/ryanzola/web3-gif-portal-client
https://github.com/FabioRocha231/SolanaPlayground
https://github.com/waterboi1729/hbot2
https://github.com/josephrubin/agora
https://github.com/TNFTM/clientpad
https://github.com/kevinee007/molana-landing
https://github.com/chilliesvo/solana-tutorial
https://github.com/ke-pan/escrow-solana
https://github.com/nabeelimran/solana-program
https://github.com/wyr241/solt
https://github.com/xdsxds007/solana
https://github.com/GottliebGlob/candy-machine-ui
https://github.com/streamdao/woocommerce-payment-gateway
https://github.com/web3bits/defund
https://github.com/siamhossain/monkey-theme-website
https://github.com/mertbezirgan/COMP491_Mint
https://github.com/BorrisMitchel/nftdrops
https://github.com/thebobfather2/bgtest
https://github.com/nikola43/NFTUISOLANABASIC
https://github.com/CognitiveArk-Lab/multi-sig-vault
https://github.com/mahdimp/solana-api
https://github.com/zdbrig/CES-Solana-Client
https://github.com/PandaDevA/solana_nft_marketplace
https://github.com/marianlopezaz/solana-tutorial
https://github.com/Taka0310/solana-escrow
https://github.com/Habeebtoyin/Solana_website
https://github.com/snehendu098/rare-vamp-mint
https://github.com/mataperezluis/populartnfttest
https://github.com/wescopeland/hubble-sp-autocompounder
https://github.com/metadiego/sol-crm-be
https://github.com/PandaDevA/metaplex
https://github.com/coladimeji/helios-repo
https://github.com/CleverChuk/sol-contract
https://github.com/mahmudsudo/solana_implementation
https://github.com/nhadi44/lil-akari-222
https://github.com/TechWebGuy/fetch-nft
https://github.com/PrivetPoka33/c
https://github.com/blockworks-foundation/voter-stake-registry
https://github.com/0xBreath/twitter-oauth-client
https://github.com/DappStarter/precious-niklufarn-9nCC
https://github.com/DappStarter/brave-longhifquim
https://github.com/DappStarter/diligent-upobek
https://github.com/DappStarter/excited-hileshop
https://github.com/ianbrdeguzman/solana-wallet-dapp
https://github.com/siskos-k/MetaSpace-Wars
https://github.com/Unboxed-Software/solana-ping-frontend
https://github.com/HarrisonPierce/Solidity-Starter
https://github.com/gypto/SolanaNFT
https://github.com/olafsnow45/associated-token-account-in-rust
https://github.com/manny22isaac/escrow
https://github.com/karimelshaarawy/Dex-late-may
https://github.com/mercurial-finance/stake-ui-v2
https://github.com/DaviDvD1/SnakeRS-Official-Mint
https://github.com/PrivetPoka33/b
https://github.com/lizengping-hub/temperature
https://github.com/DappStarter/alert-paleli-nHfB
https://github.com/DappStarter/right-quogesteg-CNPW
https://github.com/z330789559/mint_nft
https://github.com/tigthor/pool
https://github.com/littleboycoding/solana-example
https://github.com/Lit-Jesus/candy-fix
https://github.com/jordanpuri/solana-twitter
https://github.com/mihailo-maksa/candy-machine-ui
https://github.com/yohanGuerraz/blockchaine
https://github.com/serpentacademy/Get-all-transactions-mint-signed-NFTs
https://github.com/daxherrera/seanies
https://github.com/Cameron8817/NFT-Marketplace
https://github.com/coderasha/Serum-Dex
https://github.com/CaptSly/chicpayv2
https://github.com/hylsceptic/solana-escrow
https://github.com/rabcau/solana-tutorial
https://github.com/olderdev1003/solana-helloworld
https://github.com/Markuwa/testingmint
https://github.com/banana-wallet/adapter
https://github.com/mashharuki/SolanaNFTDropApp
https://github.com/Requiem-AI/arberling
https://github.com/devrose901/ntf-staking
https://github.com/DappStarter/festive-julyee-rjRD
https://github.com/DappStarter/amused-quebumie-hW6n
https://github.com/ricardocr987/escrow-v2
https://github.com/PandaDevA/HerosNFT_marketplace
https://github.com/Stephegbenga/holatest
https://github.com/SOLAXDEX/swap
https://github.com/vivekrao1985/solana-start
https://github.com/chainGossip/Keroverse_Staking
https://github.com/Lkemp1790/HOCStore
https://github.com/VishyFishy02/Minting-Website
https://github.com/harshasomisetty/nftamm
https://github.com/nikola43/solana-nft-breeding
https://github.com/smile930307/solana-nft-breeding
https://github.com/serpentacademy/send_sol
https://github.com/genuine-developer/NFT-breeding-with-anchor-on-solana
https://github.com/kevinee007/arcryptiannft-breeding-solana
https://github.com/mferrara625/Solana_Escrow
https://github.com/flipthetip/testtest
https://github.com/Vampo7152/mint
https://github.com/jackretterer/theBallerSocietyMint
https://github.com/tronginc/buildspace-solana-gif-portal
https://github.com/ebisfo/PoopyheadsSite
https://github.com/flipthetip/staking2
https://github.com/drsaint1/scope-stake
https://github.com/fl1p3mth3b1rd/try_gemfarm
https://github.com/faikarghas/paranoid-slay-staking-ui
https://github.com/MLH-Fellowship/NFTCraft
https://github.com/autocorrectoff/solana_tokens_poc
https://github.com/Alexia1305/Diplomes
https://github.com/neoxolotl/airdrop-project-final
https://github.com/lawmeskiviahs/PDA_Anchor_0-0.24.2
https://github.com/emberfarkas/musicz-solana
https://github.com/levi522/r3-marketplace
https://github.com/blockchainshifu/ProgramDeployPlatform
https://github.com/funcountry/token-experiments
https://github.com/Tincon1/SOLFeeReedemer
https://github.com/Seto0125/solana-NFT
https://github.com/ThomasCanCode/crypto_girls_generator_b00n
https://github.com/ultronDebugs/oneNftMintService
https://github.com/1zain-haider1/Eth-project-frontend
https://github.com/abhirambsn/web3-buildspace-gifportal
https://github.com/ArturCripto/holders-win
https://github.com/DescartesNetwork/sen-idl-parser
https://github.com/NiftyRewards/nifty-rewards-interface
https://github.com/Rask467/escrow-test
https://github.com/Dragonwarrior1234/nft-football
https://github.com/socr102/Raffle_Solana
https://github.com/noseagenft/mint-site
https://github.com/brwist/ninja-profile
https://github.com/Giffen-good/scrape-and-mint-nft
https://github.com/DappStarter/efficient-bopiku-bwDR
https://github.com/DappStarter/elegant-huekotin-J8Pt
https://github.com/KillerJi/solana_program
https://github.com/longmengua/contract-solana
https://github.com/coderasha/Solana-NFT-Marketplace
https://github.com/danmt/drill-poc
https://github.com/nlgtEA/test-sol
https://github.com/SmartWebstar/metaplex-1
https://github.com/alpha-defi/raydium-frontend-iframe
https://github.com/narakarax/asdda
https://github.com/nova-launch/withdraw-royalties
https://github.com/Ether0405/solana-bpf-program-template
https://github.com/Nikejan/Solana.dev
https://github.com/BoBanner420/Ganjaa
https://github.com/Sharvinm05/candy-machine-v2
https://github.com/Emma66886/buullsolanawork
https://github.com/U1tra-Labs/solana-program-library
https://github.com/XP-NETWORK/xpjs
https://github.com/ibm9471/react_solana_nftviewer
https://github.com/glow-xyz/nftoken
https://github.com/Rahuls-Cool/Gamerverse
https://github.com/ZengGang315/solana-nft-marketplace
https://github.com/vladyslavtopdev/React-Animation-LandingPage
https://github.com/ttejas123/tiktok-clone
https://github.com/viaprotocol/web3-wallets
https://github.com/KJK-Nice/point-of-sale
https://github.com/manuwor/Hotel-Dementia-Mint
https://github.com/kingtiger666/SolanaNFTBot
https://github.com/incrediblegig/solana-front
https://github.com/0xwata/solana-dapps-sample
https://github.com/ZhoufangErqiangu/chating
https://github.com/Danlowe95/Explorio
https://github.com/megaman0619/assetbender_ts
https://github.com/crypticmeta/raffle
https://github.com/imhyeonji/solana-nft-viewer
https://github.com/DappStarter/amused-diquepu-dk6r
https://github.com/DappStarter/regular-deflooslu-Gpbj
https://github.com/DappStarter/fluffy-inastfar-G6Pg
https://github.com/hordur84/rust-solana-rpc
https://github.com/thibauddr/cryptocurrency_solana
https://github.com/jokerrobert920/my-love-rust
https://github.com/meloket/divvybet-divvy-v1
https://github.com/Tirka/revertable
https://github.com/masnasri-a/minter
https://github.com/steerc2217/Kami-no-Kage
https://github.com/talentd1223/ColorPunx
https://github.com/JonathanTFairy/Dummy-Solana-Market
https://github.com/DappStarter/nimble-sobaque-gJmf
https://github.com/BunnyNomics101/nftloans
https://github.com/Kevin-Heleodoro/solana-frontend-experiment
https://github.com/thebase666/web3-solana-react-gif-collection
https://github.com/ConstaXI/nft_drop_solana
https://github.com/tanmay630/Solana-Giffs-App
https://github.com/kherincalderon/solana-nft-drop
https://github.com/warlyware/solana-nft-mint-base
https://github.com/beekay2706/Random-NFT_Drop-Dapp
https://github.com/manuochoa/solana-pay
https://github.com/dao-xyz/protocols
https://github.com/TechWebGuy/solana_web3_demo
https://github.com/hodlen/serum-testbed
https://github.com/walker1992/stake-reward
https://github.com/DappStarter/graceful-kebali-K69q
https://github.com/DappStarter/glossy-ipebed-BJJN
https://github.com/A-RonWhite/node-apy-api
https://github.com/nicogioino/solana-meme-portal
https://github.com/angel9015/Vue-Cropper
https://github.com/Rindt/nft-drop-project
https://github.com/c-exinsco/nft-drop-starter-project
https://github.com/Umairhassan5/nft-new-project
https://github.com/neoxolotl/nft-drop-starter-project-final
https://github.com/waqarmm/solana-airdrop
https://github.com/Metacrafters/challenge1-solana
https://github.com/rickygquick/potprincess
https://github.com/galaxy-comet/solana-serum-dex-main
https://github.com/IAmad-abd/Tripe
https://github.com/IAmad-abd/Xyaku
https://github.com/eRikaNFT/SolAzukiNFT
https://github.com/cutemonstersnft/test-svelte-deploy
https://github.com/smettu1/staked_vote
https://github.com/ryanzola/solana-pay
https://github.com/jdaniel96/BalanceAndMintUI
https://github.com/Brianconn71/airdrop-project-solana
https://github.com/monomadic/tutorials
https://github.com/94ljy/nestjs-test
https://github.com/sanjeetunited100/sol-launch
https://github.com/RAKESH32/solana-message
https://github.com/ffakira/example-helloworld
https://github.com/amilz/solana-playground
https://github.com/jpass022/SAFE
https://github.com/baunvb/upfi
https://github.com/redazul/solana_reactjs
https://github.com/parasol-finance/presale-application
https://github.com/sunguru98/merkle-solana-claim
https://github.com/c-exinsco/solana-pay
https://github.com/galaxy-comet/solana-dex-main
https://github.com/axonitte/debonairtest
https://github.com/AlphaPlusVN/AMeta-nodejs-solana
https://github.com/Blockchain-Team-become-Millionaire/solana-scity
https://github.com/mixelpixel/forked.one.adept.solana
https://github.com/FedererKK/Bootcamp
https://github.com/Masangri/buildspace-sol-gif-portal-backend
https://github.com/PurpleZone/NFTs
https://github.com/pnkfluffy/solana-candy-factory
https://github.com/DappStarter/fabulous-shenafay-P7Bc
https://github.com/alchemist0803/NFT-market
https://github.com/InCrypto-io/solana-dice
https://github.com/solana-labs/solminer
https://github.com/turnyay/sixtyfourgame
https://github.com/paul-schaaf/solchess
https://github.com/tsnyder701/everybuddy
https://github.com/solana-labs/example-tictactoe
https://github.com/thierryskoda/solana-pay-tutorial
https://github.com/Shivam-Riyar/fb-solana
https://github.com/Abhijit20112003/facebook__solana
https://github.com/steve-kennedy/evangelion-pixels
https://github.com/xiecy/xdapp-cpi
https://github.com/YLSMW/ExchangeBooth
https://github.com/Tincon1/Ganjapreneurs
https://github.com/Sharvinm05/nft-demo
https://github.com/leongal/candy-machine-v2-update
https://github.com/milanhpatel/solana-tutorials
https://github.com/esc8p/solanabet-frontend
https://github.com/ottoRothmund/solana-test
https://github.com/solster-finance/solster-finance
https://github.com/enjie1337/owlchemist_v2
https://github.com/efrengarcial/demowallet
https://github.com/keramostech/keradex
https://github.com/Onespace-Project/1space-DEX
https://github.com/TheCre8tor/solana-escrow
https://github.com/TheArtintheRaw/gsolminter
https://github.com/Pietro-Lungarini/wherescrypto
https://github.com/zayn-kahn/app
https://github.com/MrRob100/nft-cany-drop
https://github.com/dhruvsol/collab-nft
https://github.com/0xdeepmehta/gari-poc
https://github.com/mdepree5/hellomoon-takehome
https://github.com/rolandgvc/nexhack
https://github.com/The-Great-Ape/client
https://github.com/frakt-solana/frakt-web
https://github.com/Henry-bee/metaplex
https://github.com/aacsspkt/zebec-dca
https://github.com/truedandyman0617/tokean-ata-cli
https://github.com/webdev0627/NFT-auction-frontend_raffle
https://github.com/dialectlabs/mango-monitoring-service
https://github.com/nftsoul/nft-borrow-lend
https://github.com/legendaryphoenixicarus/spl-token-lending-client
https://github.com/DDS-TuanLD/solana-react-demo
https://github.com/Tincon1/test123
https://github.com/srirampraveenva/moralis-web3auth
https://github.com/SovereignPrime/rise-back-end
https://github.com/marsniper27/Chronicles_Character_manager
https://github.com/kevinrodriguez-io/web3-auth
https://github.com/yukiyamamuro/solana_dapp
https://github.com/opeoyeleke/solcrypt-dex
https://github.com/sqoin/solana-web-tools
https://github.com/CedYF/Clay-Mummify
https://github.com/solongwallet/instruction-parser
https://github.com/Man-from-earth25/Aladdin
https://github.com/PandaDevA/next-js-11-registration-login-example
https://github.com/zunairajaved/building-escrow
https://github.com/Shyft-to/shyft-frontend
https://github.com/leedsrising/Storefront-with-solana-pay
https://github.com/zengmengxue/solana-pay-tutorial
https://github.com/MatthewPrashker/mangoBot
https://github.com/Yash472001/solana_nft
https://github.com/davonjagah/sol-compliance
https://github.com/yoshidan/solana-auction
https://github.com/kiemtienonline360/solana-lite-metamask
https://github.com/AudiusProject/audius-client
https://github.com/trustee-wallet/trusteeWallet
https://github.com/OneKeyHQ/onekey-extension
https://github.com/Moonlet/wallet-app
https://github.com/pokassun/parrot-demo
https://github.com/Ccoda26/ShopTransactionSolana
https://github.com/Iceymann18777/dapp-scaffold
https://github.com/mean-dao/mean-msp-sdk
https://github.com/BlackenedBettencourt/solana-transfers
https://github.com/GenesysGo/shadow-drive
https://github.com/SSLockStar/SolpayUI
https://github.com/shypkov/upsite
https://github.com/pratik-mk/Decense
https://github.com/straightfrench/abstratica-old
https://github.com/jdaniel96/candy-machine-ui
https://github.com/m1d1x/mint6
https://github.com/hieudoanm/pokemon
https://github.com/alpha-defi/raydium-widgets-demo
https://github.com/tungnt2k/update-metadata-metaplex-nft
https://github.com/robertkottelin/vaccine-journaling-system
https://github.com/altaga/Project-Kharon
https://github.com/ledamint-IO/anchor-22
https://github.com/Julpine/chatbox
https://github.com/cryptoguy55a/solana-staking-frontend
https://github.com/DescartesNetwork/sen-scripts
https://github.com/Aadhinana/solana-read-retrieve
https://github.com/Muhammad-Hasham-Khalid/web3-phantom
https://github.com/harun0901/solana_dapp
https://github.com/wozgun/spl-token-bonding
https://github.com/0fatih/solana-escrow
https://github.com/TeamFunGuyz/funguyz-web
https://github.com/SushanGhimire/web3-solana-react-typescript
https://github.com/ChrisAbdo/Spotify-Solana
https://github.com/ByeongHunKim/ts_solana_web3
https://github.com/nice-chute/lulo-dex-ui
https://github.com/MoneshROR/full_stack_solana
https://github.com/thearyanahmed/sol3
https://github.com/daniel-kung/init
https://github.com/snowleopard610/solana-scaffold
https://github.com/soydulceangelina/react-phantom-connect
https://github.com/3dvolt/Metaplex-AutionHouse-UI
https://github.com/GlassEaters/justmint
https://github.com/prince2115/Tokenitis-prince2115
https://github.com/alextmn/icc_token
https://github.com/ninja-space/NFTMarketplace_offer
https://github.com/xuanbao2008/solana-nft-fiat-wallet
https://github.com/ConnyFy/solana-nextjs-template
https://github.com/Coding-and-Crypto/Solana-NFT-Marketplace
https://github.com/Anavarren1997/BetterHWSolana
https://github.com/parkergelinas/Rust
https://github.com/vamsinole/magic_hat_ui
https://github.com/DappStarter/fabulous-nenige-BktN
https://github.com/trezm/solana-bug-example-1
https://github.com/wasmium/CustodianProgram
https://github.com/ireneio/solana-contract
https://github.com/giorgiocc/account-program
https://github.com/nightfury1111111111/solana_nft_staking
https://github.com/DescartesNetwork/sen-connector
https://github.com/black-wyvern-dev/Honey_Pot_DAO
https://github.com/ChoiceCoin/Compliance
https://github.com/vamsinole/magic_hat_tshht
https://github.com/ehsansaleh155/CryptonSolanaDonation
https://github.com/teledima/solana-test
https://github.com/metasal1/sns-api
https://github.com/lawmeskiviahs/solana-program-client-example
https://github.com/radumarica/rizwan
https://github.com/radumarica/test-vercel
https://github.com/Shyft-to/shyft-solana-api
https://github.com/Naguumo/solana-dust-sweeper
https://github.com/baileyspraggins/gm-anchor
https://github.com/vchernetskyi993/voting-poc
https://github.com/LoboVH/candyMachine
https://github.com/buidler-hub/solkudos
https://github.com/DappStarter/joyous-maleyar-9FH7
https://github.com/DappStarter/magical-jobjubif-h6GM
https://github.com/sudhir-b/deserialise
https://github.com/AnishDe12020/solana-twitter
https://github.com/StefosGeo/stake-client-gm
https://github.com/kmurdzek/TheKnowledgeAcademy
https://github.com/peacemind/solana-anchor-react
https://github.com/ClockChainXD/gosawithmodal
https://github.com/avatarfreak/solana-airdrop
https://github.com/lawmeskiviahs/spl-token-transfer
https://github.com/AD-Forensics/Swan-Token-Audit
https://github.com/sonhaaa/ahnos.io
https://github.com/sarhugo/vue-candy-machine-ui
https://github.com/0fatih/solana-gif-portal
https://github.com/armujahid/solana-voting
https://github.com/captian210/metaplex
https://github.com/talented0312/NFT_Doll
https://github.com/bedrock-foundation/bedrock
https://github.com/DappStarter/educated-gejuebhoum-G9zr
https://github.com/elitedev09/candy-machine-v2
https://github.com/DappStarter/silly-kukikad-nMcG
https://github.com/0xBreath/geyser_indexer
https://github.com/maweiche/solana-pay
https://github.com/pengxjwawa123/renting-ui
https://github.com/luohaha/solana-gobinding-demo
https://github.com/talha4real/updatedmeta
https://github.com/acehood0126/reactdiscordsolana
https://github.com/abh1/pubgov-cpi
https://github.com/danmt/event-manager-dump
https://github.com/DescartesNetwork/sen-parser
https://github.com/c410-f3r/lucia
https://github.com/DappStarter/nice-tigofee-6Jrz
https://github.com/DappStarter/fluffy-pruglaje-W8dn
https://github.com/Y0h4n3s/xen-token-client
https://github.com/DappStarter/brave-rosislou-jwbR
https://github.com/VerifiSari/VerifiSari_Solana
https://github.com/DappStarter/calm-kejaha-tCRR
https://github.com/kumarbiplob336/Learn-Solana
https://github.com/marianod11/alprestreeeeee
https://github.com/Gostai/custom-wallet
https://github.com/NormanDevRepo/nft-marketplace
https://github.com/solana-fm/step-program-library
https://github.com/DappStarter/perfect-igufit-k69F
https://github.com/ShortGun2021/solanaNFT-30-05-2022-
https://github.com/loayei/SolanaContract
https://github.com/JRB-y/solana-roulette
https://github.com/giorgiebanoidze25/parasol-finance
https://github.com/lempiy/nft-bazzar
https://github.com/DappStarter/lovely-bisstamack-Hmkg
https://github.com/3tomcha/solana_fullstack
https://github.com/NftCodeForest/NftCodeForest
https://github.com/ayonsaha2011/solana-app
https://github.com/danmt/nx-dapp
https://github.com/femiswosh/dapp-solana-defi
https://github.com/Aparna-Bindhu/solana-ride-sharing
https://github.com/cavanmflynn/solsnap
https://github.com/reactdev-star/tictactoe-solana
https://github.com/sol-farm/scrapers
https://github.com/DappStarter/silly-eppeyig-LCwq
https://github.com/DappStarter/lyrical-sirohu-NqKt
https://github.com/BASCDAO/web3-map
https://github.com/0xPratik/update-metadata
https://github.com/DappStarter/excited-rudusep
https://github.com/DappStarter/warm-queptepog
https://github.com/DappStarter/gorgeous-toobooja-Qg8p
https://github.com/DappStarter/tasteful-pebeyul
https://github.com/DappStarter/dashing-merodak-GNG9
https://github.com/orca-so/whirlpools
https://github.com/zamia/solana-derivation-path-demo
https://github.com/oliverchang0330/solana-dapp
https://github.com/simba126/frontend-coffee
https://github.com/hfish7789/Solana-Course
https://github.com/Alfie/parkerprobe
https://github.com/setmax/solana-nft-refund
https://github.com/vieiralucas/soulette
https://github.com/K-D0T/solanapay
https://github.com/Ugbahaski/app
https://github.com/solape-dex/vrf-raffle
https://github.com/apoorvdwi/MusicWorld
https://github.com/NdeemSayyed/scratch-dashboard
https://github.com/0xSeaj/gmoot-table
https://github.com/josh199483/solana-web3-test
https://github.com/nfcurti/litjesus
https://github.com/xtreme911/metaplex
https://github.com/prkshtshrm4/metaplex1
https://github.com/PandaDevA/kraken_lottery
https://github.com/f44z/encode-solana-bootcamp-project
https://github.com/Inpulsgor/pay-to-play
https://github.com/DappStarter/nifty-kreluco-pdtg
https://github.com/tinkerkode/solana-pay-starter-main
https://github.com/idelgado/solana-lottery-program
https://github.com/rzoq88/guma
https://github.com/Amit8206/NFT-Metaplex
https://github.com/anj-powr/nft-starter
https://github.com/nihalanisumit/twitter-solana-dapp
https://github.com/ibrohimkhan/solana-rpc-client-example
https://github.com/maweiche/solana-nft-mint
https://github.com/Tonyce/nftmint
https://github.com/flyingsaucerx/hawksight-staking-helper-code
https://github.com/pyth-network/governance
https://github.com/CorinneBosch/spl-wallet
https://github.com/Iceymann18777/solminer
https://github.com/Kamilovkz/nft-arweave
https://github.com/crypt0miester/cm-with-signer
https://github.com/oliverchang0330/solana-twitter
https://github.com/DappStarter/accurate-wahotay-LhFF
https://github.com/piavgh/solana-pay
https://github.com/kiasaki/multisig-ui.sol
https://github.com/bstar1209/sol_em_poker
https://github.com/tobiadiks/roulette
https://github.com/kingtiger666/radium-staking
https://github.com/Jang-Wonjong/PJT-Solniverse
https://github.com/blackgar/Solniverse
https://github.com/trust0212/solana-nft-minting-site-2021-10-08
https://github.com/Rolex01/solana_learning
https://github.com/shockValue666/ccc
https://github.com/DappStarter/unbiased-loshquitof-PQLD
https://github.com/DappStarter/faithful-pequokak-Gjdr
https://github.com/Man-from-earth25/fiverr-krypt
https://github.com/alimodarresi/solana-twitter-anchor
https://github.com/SolanaEngineer0502/truesight_protocol
https://github.com/jpcaulfi/northwestern-hackathon-demos
https://github.com/cooperateDev/solanaNftStaking
https://github.com/DappStarter/talented-eyolnal-H6PF
https://github.com/DappStarter/sincere-capetrue-Wwn8
https://github.com/DappStarter/smart-shijoma-GfQM
https://github.com/saulofsouza/study_solana
https://github.com/IAmad-abd/HeavenL
https://github.com/wentokay/catch-example
https://github.com/madrugada-labs/staking-v1
https://github.com/thomas0114/solana_nft_mint_metaplex-air-world-
https://github.com/shopeyin5/Mainnet
https://github.com/nhadi44/mutant_tripping-ape
https://github.com/mojalil/solana-escrow
https://github.com/DappStarter/zany-giratiern-7D9T
https://github.com/DappStarter/funny-segore-hLJM
https://github.com/KJK-Nice/solana-pay-starter
https://github.com/SecretStarLight/Sol-Swap
https://github.com/SharkyFi/client
https://github.com/ireneio/onepage-template
https://github.com/captian210/konceptual-frontend
https://github.com/EVOAUCTION/kyule
https://github.com/desertidaho/nft_market
https://github.com/farhanali2325/solana-metaplex
https://github.com/badass-commits/anchor-v12
https://github.com/nfcurti/moonwalkers
https://github.com/sceptre520/spltoken_transfer
https://github.com/mmbmha/testingnft
https://github.com/Bojidar00/solana-voting-client
https://github.com/tinwritescode/o2-candy-machine
https://github.com/leongal/metaplex
https://github.com/DappStarter/cultured-abutim-kJNP
https://github.com/Zaid-maker/spotify-blockchain
https://github.com/thedonmon/sol-template-wallet
https://github.com/Shaik-Sirajuddin/Minting-UI
https://github.com/christophercelaya/solana-candy-machine
https://github.com/kronus-protocol/tictactoe-contract
https://github.com/patrickwide/solana-program
https://github.com/DappStarter/flowery-garuequum-n7rB
https://github.com/DappStarter/capable-eyiebes-8kw7
https://github.com/KhalilJouaneh/Solana-Airdrop-Program
https://github.com/mvcmvvm/mytestproject
https://github.com/guilleBFG/solana-web-app-solana-contract
https://github.com/DappStarter/regular-quasuda-JBmh
https://github.com/stroberrysugar/testanchor
https://github.com/opub/floor-sweeper
https://github.com/rohit-710/Web3GifPortal
https://github.com/fabric-foundation/fabpunkbot
https://github.com/davincci9412/HPadBridge
https://github.com/riz1-k/palmverse
https://github.com/DappStarter/bouncy-quigero-K7jf
https://github.com/DappStarter/gentle-niluque-k6RP
https://github.com/DappStarter/confident-sekulo-jzdb
https://github.com/IAmad-abd/sol
https://github.com/Abusayid693/DeFi-reddit
https://github.com/Yogeshkumar170201/gif-portal
https://github.com/maksimonishchenko/metaplex
https://github.com/Texaglo/meaplex_experiment
https://github.com/fl1p3mth3b1rd/try_nft
https://github.com/danielionashku/solana
https://github.com/pablomunozcoronas/solana
https://github.com/supermean-ayaz/msp-sdk
https://github.com/ZouaouiK/tcp_stream_portfolio
https://github.com/brson/solana-token-maker
https://github.com/harmonia-eko/ignition-v4
https://github.com/tungnnt/sol-wallet-reg
https://github.com/hwsimmons17/GrowthGate_NFT
https://github.com/Solottery/Backend
https://github.com/IAmad-abd/SF
https://github.com/Bicabo98/Solana-DAPP
https://github.com/christophercelaya/solana-mint-page
https://github.com/solsavant/candy-machine-ui
https://github.com/olafsnow45/token_mint-trans_fee_split
https://github.com/NosenkoVladislav/nft-website-sh
https://github.com/XOTTABY4/candy-machine-ui_mint_remain_JAPE_count
https://github.com/KellianDev/solana-airdrop
https://github.com/IIM-Creative-Technology/NODEJS-SOCKETIO-IIM-DW1-API_HEDDIBU
https://github.com/anselsol/letsgetit
https://github.com/kenwambu1914/tiktock-solana
https://github.com/alchemistgo87/mint-info-app
https://github.com/snowMan108/nft
https://github.com/luisazevedo01/Solsong
https://github.com/MaksymLutsiv/pixward-games-test
https://github.com/NedenSinir/minting-demo
https://github.com/monkey-king-jim/solana-twitter
https://github.com/Rust-Coding/facebook-solana
https://github.com/mehranfotovat/send_sol
https://github.com/d-arde/solanaTPS
https://github.com/starfoxbeta/artbombmetaplex1
https://github.com/zamia/laag-web-wallet
https://github.com/crysis1201/multisig_ui
https://github.com/zachchoi12/solana-social
https://github.com/AdamReinmuller/multisig
https://github.com/peeper35/example-random-number
https://github.com/zangcoder-0210/Solana-Swap-UI
https://github.com/KingFavourCreates/Solana-Candy-Factory
https://github.com/baselm/JODC
https://github.com/danmt/demobase-labs
https://github.com/baselm/Crypto-Islamic-Financing
https://github.com/abacus-x/solana-tx-serialization
https://github.com/ankaszatanka/fairTradeCoffee
https://github.com/graysonsteakley/tiktok-clone
https://github.com/harlexkhal/cryptex-solana
https://github.com/benjaminbascary/Challenge_tecnico
https://github.com/mwangiismuthui/mycalculatordapp
https://github.com/iigunchev/phantom-wallet
https://github.com/ExtremelySunnyYK/solana-contracts-basics
https://github.com/cleon30/Solana-Practise-Rust
https://github.com/dbricks-xyz/dbricks-ts
https://github.com/UniOasis/solana-program-instrcutions
https://github.com/shalinCS/UTNFT-Beta
https://github.com/honeydefi/NFT-farm
https://github.com/ningxin18/solana
https://github.com/ibrica/money-stream
https://github.com/tomjpandolfi/frontend-varrock
https://github.com/JulienWebDeveloppeur/Mokie-s
https://github.com/jrayoub/wallet-backend
https://github.com/tctien342/solana-anchor-sample
https://github.com/DappStarter/diligent-eyiedpem-9ddr
https://github.com/nina-market/nina
https://github.com/klaytn/tx-latency-measurement
https://github.com/Cisharper/script-rc
https://github.com/highlya/metaplex
https://github.com/marksikaundi/TikTok-yt
https://github.com/Vampo7152/candy
https://github.com/Dragonwarrior1234/Candymachine-with-marketplace
https://github.com/DovakhinX/Sol-mint
https://github.com/shopeyin5/MintTemplate
https://github.com/codebender828/mtalk-webpack
https://github.com/Sapien-news/pubgov-master
https://github.com/kin-starters/kin-dapp-mogami
https://github.com/KaKeimei/anchor-helloworld
https://github.com/tinkerbell07/famecoin-solana
https://github.com/unchain-dev/solana-wallet-starter-project
https://github.com/nice-chute/ui-v1
https://github.com/teqie-io/vote4mee-fe
https://github.com/q1sm4t/cyrtpo-pitbulls
https://github.com/quangtran8588/SolanaSMCPractice
https://github.com/saber-hq/merkle-distributor
https://github.com/jamiefinlayson/solana-candy-factory
https://github.com/Vampo7152/candy-machine
https://github.com/daxherrera/seanies-candy-machine-ui
https://github.com/duythien0912/noxal-nft-mint
https://github.com/AleLaBestia/tiktok-solana
https://github.com/ross406/tiktok-solana
https://github.com/formiat/example-helloworld
https://github.com/NakedKoala/POC
https://github.com/neonlabsorg/multisig
https://github.com/SajidXRizvi/CandyFac
https://github.com/wjl8/wish
https://github.com/amblade/solnftmintapp
https://github.com/sampsonbryce/solana-candy-factory
https://github.com/baselm/spl-wallet-jodc
https://github.com/Kamikazeb/Qwetas-NFT
https://github.com/mmbmha/NFTMintingDev
https://github.com/topcook/solana-string-append-program
https://github.com/psecuresystem/Decentratok
https://github.com/cryptoguru1024/-Solana_NFT_marketplace
https://github.com/staccDOTsol/noCopeHere
https://github.com/gyan0890/RustStudyGroupEscrow
https://github.com/redsky500/Shine_Finance_Frontend
https://github.com/richapillai/athena
https://github.com/everstake/eversol-ts-sdk
https://github.com/sigridjineth/solana-twitter
https://github.com/DitJee/Auction-House
https://github.com/gg658/CropperFinance
https://github.com/Harry-Potter415/Minting-NFT-Solana
https://github.com/protonwebmaster/adrenogenesis-metaplex-2
https://github.com/jessupjn/switchboard-epl-feeds
https://github.com/bbidarian/metaone
https://github.com/FAvE01/BRX-LAB
https://github.com/mecoolmendi/w-whales
https://github.com/ris-2107/sg2
https://github.com/stream-protocol/payment-gateway
https://github.com/carbondesigned/ShareDeso
https://github.com/Asjad-Waseem/spicy-chicken-frontend
https://github.com/jaxeaxe/aaa
https://github.com/noFAYZ/bvll-g
https://github.com/ris-2107/SGnft
https://github.com/mairh/nftkit
https://github.com/AhmadLpsn/crowdfunding-platform-client
https://github.com/fastbreaklabs/contracts
https://github.com/kenwambu1914/solana-smart-contract
https://github.com/tearaku/dapp-final
https://github.com/Meachers/XPEARMINT
https://github.com/plats-network/plats-solana-contract
https://github.com/nightly-labs/solana-adapter
https://github.com/DappStarter/loving-pikorcon-cF9Q
https://github.com/DunnCreativeSS/bitstacc
https://github.com/ksivane/solana-ce
https://github.com/mathieu-chauvin/Betly
https://github.com/vasanth913/Solona_Sdk
https://github.com/Mercutio14/YamaSquadNFT
https://github.com/PandaDevA/Solana_CLI_Typescript
https://github.com/LowLowCoder-Mel/solana-contract-demo
https://github.com/Bicabo98/candymachine-v2-boiler-mint-site-noFLP-main
https://github.com/fennyflop/curly-system
https://github.com/aaely/web3-template
https://github.com/nightfury1111111111/aces-card-solana
https://github.com/rocalex/solana-pda-demo
https://github.com/exiled-apes/candy-holders
https://github.com/Validator-Wars-Dapp/Stake-Pool
https://github.com/johnrees/treeshake-example
https://github.com/solanasail/tipsailbot
https://github.com/uttarayan21/hello-world-solana
https://github.com/meloket/divvybet-metaplex
https://github.com/dany-armstrong/sol-todo-list
https://github.com/SolanaTrade/Trade
https://github.com/davidzzheng/dux
https://github.com/kimura-sang/nft-art-mint-marketplace
https://github.com/erik-26/clone-kyve
https://github.com/zarex5/ngf-nft-upgrader
https://github.com/zloslavistefeev/solana-art
https://github.com/Wildebeest/askbid
https://github.com/realsbd/7f-social
https://github.com/iamoperand/cpi-example-solana
https://github.com/MrRob100/mycalculatordapp
https://github.com/rai-rakesh/solana-escrow
https://github.com/SolSpaceHamster/api.solhamster.space
https://github.com/black-wyvern-dev/solana-spl-faucet
https://github.com/proxycapital/discord-bot
https://github.com/cryptodev26/Solana-Condor-NFT-Minting-CM-v2
https://github.com/WarringNations/test-candy-machine-1
https://github.com/ahsan-arif/candy-machine-mint
https://github.com/fyfylian/stream-payment
https://github.com/klemenkerin/pixsol
https://github.com/Thatguywill12/immortal-babes
https://github.com/ceramicanft/devnet_test
https://github.com/gigabit-eth/martiancandy-v2
https://github.com/ojiubasi-motif/template
https://github.com/topcook/solana-counter-program
https://github.com/ysednevgit/solana-bpf-program
https://github.com/giorgiebanoidze425/dracula-game-app
https://github.com/SyedArifulIslamEmon/tiktok-solana
https://github.com/certusone/xdapp-book
https://github.com/alpha-sol/alpha-frontend
https://github.com/synergy-hyperledger/solana-kyc-program
https://github.com/metablockshq/metablocks.world
https://github.com/fuzzc0re/deliberatively
https://github.com/JeremyPersing/ownthatmeme
https://github.com/dialectlabs/tribeca-frontend
https://github.com/sert121/mintantly-beta
https://github.com/Aoi1011/amm
https://github.com/padhyeSohum/solana-GIF-portal
https://github.com/ZengGang315/explorer
https://github.com/JayKickliter/count-tracker
https://github.com/MathanMK/Solminter
https://github.com/theogllrd/crowd-funding-solana-program-v2
https://github.com/vikage/Solana-program-client
https://github.com/bhagyamudgal/solana-ping-client
https://github.com/primenumsdev/learn-web3-dapp
https://github.com/socksrust/xfarm
https://github.com/gatorbait-eth/anchor
https://github.com/cyrsis/wsbdegenerate
https://github.com/nick400/solana-candy-factory
https://github.com/Smikhotur/ultainfinity-exchange
https://github.com/Tichubrothers/squid-frontend
https://github.com/abh1/Sapien.News
https://github.com/wanje125/solana_nft
https://github.com/domluna/solana-tic-tac-toe
https://github.com/SuperFly005/solana-escrow
https://github.com/thegreat-vanderlinde/solana-pda
https://github.com/bhagyamudgal/solana-pay-address
https://github.com/apausa/solana-ping-client
https://github.com/igneous-labs/solana-stake-sdk
https://github.com/Fbossio/itsc_api
https://github.com/nQuery512/metaplex-goodpick
https://github.com/openweblabs/web3-elements
https://github.com/jupiter211developer/kick2win
https://github.com/vthubati/tiktok-solana
https://github.com/murataslan1/dapp-scaffold-explorer-solana
https://github.com/0xys/solana-hackerhouse-2022
https://github.com/AswinWebMob/raydium_application
https://github.com/DragonProtocol/enchaNFT-landing-page
https://github.com/fsarihan/sol-zombie-interface
https://github.com/DappStarter/fearless-eppeyig-hjDh
https://github.com/DragonProtocol/enchanft
https://github.com/Ken-tech-max/wehatescammerswebsite
https://github.com/Atomixy/atomixy
https://github.com/Unboxed-Software/solana-token-client
https://github.com/smartdev0612/gif-portal-solana
https://github.com/Grape-Labs/grape-pay
https://github.com/nireshd/studious-spoon
https://github.com/Hsien-HsiuLiao/solana-escrow-template
https://github.com/masafumimori/dApps_samples
https://github.com/RandomizerNetwork/user-interface
https://github.com/Bi-Mars/solana-counter-test--001
https://github.com/cleon30/Anchor-Counter
https://github.com/ArtemLakhurov/bitorbit-google-auth
"""

repoList = REPOS.split("\n")